// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_dynamic_form/test/fetch_form_proccess_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:flutter_dynamic_form/data/form_data_source.dart' as _i3;
import 'package:flutter_dynamic_form/data/parser.dart' as _i2;
import 'package:flutter_dynamic_form/domain/models/form_input_field_models.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFormParser_0 extends _i1.SmartFake implements _i2.FormParser {
  _FakeFormParser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FormDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormDataSource extends _i1.Mock implements _i3.FormDataSource {
  MockFormDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FormParser get formParser =>
      (super.noSuchMethod(
            Invocation.getter(#formParser),
            returnValue: _FakeFormParser_0(
              this,
              Invocation.getter(#formParser),
            ),
          )
          as _i2.FormParser);

  @override
  _i4.Future<List<_i5.InputField>> fetchForm() =>
      (super.noSuchMethod(
            Invocation.method(#fetchForm, []),
            returnValue: _i4.Future<List<_i5.InputField>>.value(
              <_i5.InputField>[],
            ),
          )
          as _i4.Future<List<_i5.InputField>>);

  @override
  dynamic submitData(
    Map<String, String>? fieldValues,
    Map<String, _i6.File>? files,
  ) => super.noSuchMethod(Invocation.method(#submitData, [fieldValues, files]));
}
